# libavcodec source files (all platforms)
set(LIBAVCODEC_SOURCE_FILES
	${LIBAVCODEC_SRC_DIR}/aac_ac3_parser.c
	${LIBAVCODEC_SRC_DIR}/aac_parser.c
	${LIBAVCODEC_SRC_DIR}/aacadtsdec.c
	${LIBAVCODEC_SRC_DIR}/aacdec.c
	${LIBAVCODEC_SRC_DIR}/aacps_float.c
	${LIBAVCODEC_SRC_DIR}/aacpsdsp_float.c
	${LIBAVCODEC_SRC_DIR}/aacsbr.c
	${LIBAVCODEC_SRC_DIR}/aactab.c
	${LIBAVCODEC_SRC_DIR}/aandcttab.c
	${LIBAVCODEC_SRC_DIR}/allcodecs.c
	${LIBAVCODEC_SRC_DIR}/atrac.c
	${LIBAVCODEC_SRC_DIR}/atrac3.c
	${LIBAVCODEC_SRC_DIR}/atrac3plus.c
	${LIBAVCODEC_SRC_DIR}/atrac3plusdec.c
	${LIBAVCODEC_SRC_DIR}/atrac3plusdsp.c
	${LIBAVCODEC_SRC_DIR}/audioconvert.c
	${LIBAVCODEC_SRC_DIR}/avdct.c
	${LIBAVCODEC_SRC_DIR}/avfft.c
	${LIBAVCODEC_SRC_DIR}/avpacket.c
	${LIBAVCODEC_SRC_DIR}/avpicture.c
	${LIBAVCODEC_SRC_DIR}/bitstream_filter.c
	${LIBAVCODEC_SRC_DIR}/bitstream.c
	${LIBAVCODEC_SRC_DIR}/blockdsp.c
	${LIBAVCODEC_SRC_DIR}/bswapdsp.c
	${LIBAVCODEC_SRC_DIR}/cabac.c
	${LIBAVCODEC_SRC_DIR}/codec_desc.c
	${LIBAVCODEC_SRC_DIR}/d3d11va.c
	${LIBAVCODEC_SRC_DIR}/dct.c
	${LIBAVCODEC_SRC_DIR}/dct32_fixed.c
	${LIBAVCODEC_SRC_DIR}/dct32_float.c
	${LIBAVCODEC_SRC_DIR}/dirac.c
	${LIBAVCODEC_SRC_DIR}/dv_profile.c
	${LIBAVCODEC_SRC_DIR}/error_resilience.c
	${LIBAVCODEC_SRC_DIR}/exif.c
	${LIBAVCODEC_SRC_DIR}/faandct.c
	${LIBAVCODEC_SRC_DIR}/faanidct.c
	${LIBAVCODEC_SRC_DIR}/fdctdsp.c
	${LIBAVCODEC_SRC_DIR}/fft_fixed_32.c
	${LIBAVCODEC_SRC_DIR}/fft_fixed.c
	${LIBAVCODEC_SRC_DIR}/fft_float.c
	${LIBAVCODEC_SRC_DIR}/fft_init_table.c
	${LIBAVCODEC_SRC_DIR}/ffv1.c
	${LIBAVCODEC_SRC_DIR}/ffv1enc.c
	${LIBAVCODEC_SRC_DIR}/flvdec.c
	${LIBAVCODEC_SRC_DIR}/flvenc.c
	${LIBAVCODEC_SRC_DIR}/frame_thread_encoder.c
	${LIBAVCODEC_SRC_DIR}/golomb.c
	${LIBAVCODEC_SRC_DIR}/h263_parser.c
	${LIBAVCODEC_SRC_DIR}/h263.c
	${LIBAVCODEC_SRC_DIR}/h263data.c
	${LIBAVCODEC_SRC_DIR}/h263dec.c
	${LIBAVCODEC_SRC_DIR}/h263dsp.c
	${LIBAVCODEC_SRC_DIR}/h264_cabac.c
	${LIBAVCODEC_SRC_DIR}/h264_cavlc.c
	${LIBAVCODEC_SRC_DIR}/h264_direct.c
	${LIBAVCODEC_SRC_DIR}/h264_loopfilter.c
	${LIBAVCODEC_SRC_DIR}/h264_mb.c
	${LIBAVCODEC_SRC_DIR}/h264_parser.c
	${LIBAVCODEC_SRC_DIR}/h264_picture.c
	${LIBAVCODEC_SRC_DIR}/h264_ps.c
	${LIBAVCODEC_SRC_DIR}/h264_refs.c
	${LIBAVCODEC_SRC_DIR}/h264_sei.c
	${LIBAVCODEC_SRC_DIR}/h264_slice.c
	${LIBAVCODEC_SRC_DIR}/h264.c
	${LIBAVCODEC_SRC_DIR}/h264chroma.c
	${LIBAVCODEC_SRC_DIR}/h264dsp.c
	${LIBAVCODEC_SRC_DIR}/h264idct.c
	${LIBAVCODEC_SRC_DIR}/h264pred.c
	${LIBAVCODEC_SRC_DIR}/h264qpel.c
	${LIBAVCODEC_SRC_DIR}/hpeldsp.c
	${LIBAVCODEC_SRC_DIR}/huffman.c
	${LIBAVCODEC_SRC_DIR}/huffyuv.c
	${LIBAVCODEC_SRC_DIR}/huffyuvenc.c
	${LIBAVCODEC_SRC_DIR}/huffyuvencdsp.c
	${LIBAVCODEC_SRC_DIR}/idctdsp.c
	${LIBAVCODEC_SRC_DIR}/imdct15.c
	${LIBAVCODEC_SRC_DIR}/imgconvert.c
	${LIBAVCODEC_SRC_DIR}/intelh263dec.c
	${LIBAVCODEC_SRC_DIR}/ituh263dec.c
	${LIBAVCODEC_SRC_DIR}/ituh263enc.c
	${LIBAVCODEC_SRC_DIR}/jfdctfst.c
	${LIBAVCODEC_SRC_DIR}/jfdctint.c
	${LIBAVCODEC_SRC_DIR}/jpegtables.c
	${LIBAVCODEC_SRC_DIR}/jrevdct.c
	${LIBAVCODEC_SRC_DIR}/kbdwin.c
	${LIBAVCODEC_SRC_DIR}/latm_parser.c
	${LIBAVCODEC_SRC_DIR}/lossless_videodsp.c
	${LIBAVCODEC_SRC_DIR}/mathtables.c
	${LIBAVCODEC_SRC_DIR}/mdct_fixed_32.c
	${LIBAVCODEC_SRC_DIR}/mdct_fixed.c
	${LIBAVCODEC_SRC_DIR}/mdct_float.c
	${LIBAVCODEC_SRC_DIR}/me_cmp.c
	${LIBAVCODEC_SRC_DIR}/mjpegbdec.c
	${LIBAVCODEC_SRC_DIR}/mjpegdec.c
	${LIBAVCODEC_SRC_DIR}/motion_est.c
	${LIBAVCODEC_SRC_DIR}/mpeg_er.c
	${LIBAVCODEC_SRC_DIR}/mpeg12.c
	${LIBAVCODEC_SRC_DIR}/mpeg12data.c
	${LIBAVCODEC_SRC_DIR}/mpeg12dec.c
	${LIBAVCODEC_SRC_DIR}/mpeg4audio.c
	${LIBAVCODEC_SRC_DIR}/mpeg4video_parser.c
	${LIBAVCODEC_SRC_DIR}/mpeg4video.c
	${LIBAVCODEC_SRC_DIR}/mpeg4videodec.c
	${LIBAVCODEC_SRC_DIR}/mpeg4videoenc.c
	${LIBAVCODEC_SRC_DIR}/mpegaudio_parser.c
	${LIBAVCODEC_SRC_DIR}/mpegaudio.c
	${LIBAVCODEC_SRC_DIR}/mpegaudiodata.c
	${LIBAVCODEC_SRC_DIR}/mpegaudiodec_fixed.c
	${LIBAVCODEC_SRC_DIR}/mpegaudiodecheader.c
	${LIBAVCODEC_SRC_DIR}/mpegaudiodsp_data.c
	${LIBAVCODEC_SRC_DIR}/mpegaudiodsp_fixed.c
	${LIBAVCODEC_SRC_DIR}/mpegaudiodsp_float.c
	${LIBAVCODEC_SRC_DIR}/mpegaudiodsp.c
	${LIBAVCODEC_SRC_DIR}/mpegpicture.c
	${LIBAVCODEC_SRC_DIR}/mpegutils.c
	${LIBAVCODEC_SRC_DIR}/mpegvideo_enc.c
	${LIBAVCODEC_SRC_DIR}/mpegvideo_motion.c
	${LIBAVCODEC_SRC_DIR}/mpegvideo_parser.c
	${LIBAVCODEC_SRC_DIR}/mpegvideo.c
	${LIBAVCODEC_SRC_DIR}/mpegvideodata.c
	${LIBAVCODEC_SRC_DIR}/mpegvideodsp.c
	${LIBAVCODEC_SRC_DIR}/mpegvideoencdsp.c
	${LIBAVCODEC_SRC_DIR}/options.c
	${LIBAVCODEC_SRC_DIR}/parser.c
	${LIBAVCODEC_SRC_DIR}/pcm.c
	${LIBAVCODEC_SRC_DIR}/pixblockdsp.c
	${LIBAVCODEC_SRC_DIR}/profiles.c
	${LIBAVCODEC_SRC_DIR}/qpeldsp.c
	${LIBAVCODEC_SRC_DIR}/qsv_api.c
	${LIBAVCODEC_SRC_DIR}/rangecoder.c
	${LIBAVCODEC_SRC_DIR}/ratecontrol.c
	${LIBAVCODEC_SRC_DIR}/raw.c
	${LIBAVCODEC_SRC_DIR}/rdft.c
	${LIBAVCODEC_SRC_DIR}/resample.c
	${LIBAVCODEC_SRC_DIR}/resample2.c
	${LIBAVCODEC_SRC_DIR}/rl.c
	${LIBAVCODEC_SRC_DIR}/sbrdsp.c
	${LIBAVCODEC_SRC_DIR}/simple_idct.c
	${LIBAVCODEC_SRC_DIR}/sinewin_fixed.c
	${LIBAVCODEC_SRC_DIR}/sinewin.c
	${LIBAVCODEC_SRC_DIR}/startcode.c
	${LIBAVCODEC_SRC_DIR}/tiff_common.c
	${LIBAVCODEC_SRC_DIR}/utils.c
#	${LIBAVCODEC_SRC_DIR}/vdpau.c	# I had this in my gmake-generated object files, but disabled hwaccels
	${LIBAVCODEC_SRC_DIR}/videodsp.c	# if we conditionally append sources to add vpdpau, need cmake find package)
	${LIBAVCODEC_SRC_DIR}/vorbis_parser.c
	${LIBAVCODEC_SRC_DIR}/xiph.c
	${LIBAVCODEC_SRC_DIR}/xvididct.c
)

# includes to ship with libavcodec
set(LIBAVCODEC_HEADERS
	${LIBAVCODEC_SRC_DIR}/avcodec.h
	${LIBAVCODEC_SRC_DIR}/avdct.h
	${LIBAVCODEC_SRC_DIR}/avfft.h
	${LIBAVCODEC_SRC_DIR}/dv_profile.h
	${LIBAVCODEC_SRC_DIR}/d3d11va.h
	${LIBAVCODEC_SRC_DIR}/dirac.h
	${LIBAVCODEC_SRC_DIR}/dxva2.h
	${LIBAVCODEC_SRC_DIR}/qsv.h
	${LIBAVCODEC_SRC_DIR}/vaapi.h
	${LIBAVCODEC_SRC_DIR}/vda.h
	${LIBAVCODEC_SRC_DIR}/vdpau.h
	${LIBAVCODEC_SRC_DIR}/version.h
	${LIBAVCODEC_SRC_DIR}/videotoolbox.h
	${LIBAVCODEC_SRC_DIR}/vorbis_parser.h
	${LIBAVCODEC_SRC_DIR}/xvmc.h
)

# OS-specific sources
if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
	list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/dxva2.c)
	list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/dxva2_h264.c)
	list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/avcodecres.rc)
	if (MSVC) # if LIBC_MSVCRT present; there may be a better/more accurate way to test for this
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/file_open.c)
	endif()
else() # To Do; threads should actually be tested for, although a POSIX system without threads?
	list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/pthread.c)
	list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/pthread_slice.c)
	list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/pthread_frame.c)
endif()

# Architecture-specific sources
# To Do - verify that we can actually use ASM on x86 in addition to x86_64; I seem to recall this being an issue
# at least on FreeBSD
if (ENABLE_OPTIMIZATIONS)
	if(CMAKE_SYSTEM_PROCESSOR MATCHES "amd64.*|AMD64.*|x86_64.*|X86_64.*|x86.*|i686.*|i386.*")
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/aacpsdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/aacpsdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/blockdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/blockdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/bswapdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/bswapdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/constants.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/dct_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/dct32.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/fdct.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/fdctdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/fft_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/fft.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/fpel.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h263_loopfilter.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h263dsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_chromamc_10bit.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_chromamc.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_deblock_10bit.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_deblock.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_idct_10bit.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_idct.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_intrapred_10bit.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_intrapred_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_intrapred.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_qpel_10bit.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_qpel_8bit.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_qpel.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_weight_10bit.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264_weight.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264chroma_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/h264dsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/hpeldsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/hpeldsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/huffyuvencdsp_mmx.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/huffyuvencdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/idctdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/idctdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/imdct36.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/lossless_videodsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/lossless_videodsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/me_cmp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/me_cmp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/mpegaudiodsp.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/mpegvideo.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/mpegvideodsp.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/mpegvideoenc.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/mpegvideoencdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/mpegvideoencdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/pixblockdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/pixblockdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/qpel.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/qpeldsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/qpeldsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/sbrdsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/sbrdsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/simple_idct.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/simple_idct10.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/videodsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/videodsp.asm)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/xvididct_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/x86/xvididct.asm)
	elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64.*|arm64.*|aarch64.*")
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/fft_init_aarch64.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/fft_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/h264chroma_init_aarch64.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/h264cmc_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/h264dsp_init_aarch64.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/h264pred_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/h264pred_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/h264qpel_init_aarch64.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/h264qpel_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/hpeldsp_init_aarch64.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/hpeldsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/imdct15_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/imdct15_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/mdct_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/mpegaudiodsp_init.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/mpegaudiodsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/aarch64/videodsp_init.c)
	elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "arm.*")
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/aacpsdsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/aacpsdsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/blockdsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/blockdsp_init_neon.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/blockdsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/fft_fixed_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/fft_fixed_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/fft_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/fft_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/fft_vfp.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264chroma_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264cmc_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264dsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264dsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264idct_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264pred_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264pred_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264qpel_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/h264qpel_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/hpeldsp_arm.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/hpeldsp_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/hpeldsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/hpeldsp_init_armv6.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/hpeldsp_init_neon.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/hpeldsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/idctdsp_arm.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/idctdsp_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/idctdsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/idctdsp_init_armv5te.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/idctdsp_init_armv6.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/idctdsp_init_neon.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/idctdsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/jrevdct_arm.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mdct_fixed_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mdct_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mdct_vfp.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/me_cmp_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/me_cmp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegaudiodsp_fixed_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegaudiodsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegvideo_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegvideo_armv5te.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegvideo_armv5te_s.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegvideo_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegvideoencdsp_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/mpegvideoencdsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/pixblockdsp_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/pixblockdsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/rdft_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/sbrdsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/sbrdsp_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/simple_idct_arm.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/simple_idct_armv5te.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/simple_idct_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/simple_idct_neon.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/startcode_armv6.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/videodsp_armv5te.S)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/videodsp_init_arm.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/arm/videodsp_init_armv5te.c)
	elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "mips.*")
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/mips/aacdec_mips.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/mips/aacpsdsp_mips.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/mips/aacsbr_mips.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/mips/h264chroma_init_mips.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/mips/h264dsp_init_mips.c)
		list(APPEND LIBAVCODEC_SOURCE_FILES ${LIBAVCODEC_SRC_DIR}/mips/sbrdsp_mips.c)
	endif()
endif()
